"use client";

import {
  MapPinned,
  TrendingUp,
  Home,
  ShieldCheck,
  Sparkles,
  Clock3,
} from "lucide-react";

export default function WhyBuyLocation({
  locationName,
  pageContent,
}) {
  // ============================================================
  // ADMIN CUSTOM CONTENT
  // ============================================================

  const customContent = pageContent?.whyBuy || {};

  // ============================================================
  // SAFE VALUE HELPER
  //
  // Non-empty admin value = use admin value
  // Empty/missing admin value = use static default
  // ============================================================

  const value = (customValue, fallback) => {
    return typeof customValue === "string" &&
      customValue.trim()
      ? customValue.trim()
      : fallback;
  };

  // ============================================================
  // HEADER CONTENT
  // ============================================================

  const eyebrow = value(
    customContent?.eyebrow,
    "WHY BUY?"
  );

  const title = value(
    customContent?.title,
    `Why Consider Buying in ${locationName}?`
  );

  /*
   * IMPORTANT:
   * whyBuy.description can now be either:
   *
   * 1. Plain text
   * 2. Rich HTML generated by RichTextEditor
   */

  const description = value(
    customContent?.description,
    `Choosing a property is about more than the individual home. Buyers often evaluate the surrounding location, connectivity, infrastructure, residential demand, quality of development, lifestyle ecosystem and the potential suitability of the address for their long-term objectives. These factors can help provide a broader framework when assessing opportunities in ${locationName}.`
  );

  // ============================================================
  // CLEAN RICH TEXT
  //
  // ReactQuill may store:
  //   &nbsp;
  //   &#160;
  //   &#xA0;
  //   actual NBSP characters
  //
  // Normalize them so they cannot cause horizontal overflow.
  // ============================================================

  const normalizeRichText = (text) => {
    if (typeof text !== "string") {
      return "";
    }

    return text
      .replace(/&nbsp;/gi, " ")
      .replace(/&#160;/gi, " ")
      .replace(/&#xA0;/gi, " ")
      .replace(/\u00a0/g, " ")
      .replace(/<p>\s*<\/p>/gi, "");
  };

  const normalizedDescription =
    normalizeRichText(description);

  // ============================================================
  // RICH TEXT DETECTION
  //
  // Detect actual HTML tags.
  //
  // Examples:
  //   <p>...</p>
  //   <strong>...</strong>
  //   <ul>...</ul>
  //   <h3>...</h3>
  //   <a href="...">...</a>
  //
  // Normal plain text is rendered normally.
  // ============================================================

  const hasRichText =
    /<\s*[a-z][^>]*>/i.test(
      normalizedDescription
    );

  // ============================================================
  // DEFAULT REASONS
  //
  // IMPORTANT:
  // These card descriptions remain PLAIN TEXT.
  // ============================================================

  const defaultReasons = [
    {
      title: "Strategic Location",
      description:
        "A well-positioned address can improve everyday convenience and broaden access to important destinations.",
    },
    {
      title: "Infrastructure Growth",
      description:
        "Infrastructure development can influence accessibility, activity and the long-term character of a locality.",
    },
    {
      title: "Residential Demand",
      description:
        "Demand from homebuyers can support the development of diverse residential communities and amenities.",
    },
    {
      title: "Reputed Developers",
      description:
        "Established developers can bring planned communities, professional execution and differentiated project offerings.",
    },
    {
      title: "Lifestyle Ecosystem",
      description:
        "A growing combination of retail, education, healthcare and leisure can enhance everyday liveability.",
    },
    {
      title: "Long-Term Potential",
      description:
        "Buyers can evaluate infrastructure, supply, demand and future development while considering long-term ownership.",
    },
  ];

  // ============================================================
  // ADMIN REASONS
  //
  // IMPORTANT:
  // Merge by position instead of replacing the entire array.
  //
  // Example:
  // Admin edits reason #2 only
  // → reason #1, #3, #4, #5, #6 remain default
  //
  // Extra admin reasons are also preserved.
  //
  // IMPORTANT:
  // Reason descriptions remain PLAIN TEXT.
  // ============================================================

  const customReasons = Array.isArray(
    customContent?.reasons
  )
    ? customContent.reasons
    : [];

  const reasonsLength = Math.max(
    defaultReasons.length,
    customReasons.length
  );

  const reasons = Array.from(
    { length: reasonsLength },
    (_, index) => {
      const fallback =
        defaultReasons[index] || {
          title: "",
          description: "",
        };

      const custom =
        customReasons[index] || {};

      const title = value(
        custom?.title,
        fallback.title
      );

      const description = value(
        custom?.description,
        fallback.description
      );

      return {
        title,
        description,
      };
    }
  ).filter(
    (reason) =>
      reason.title ||
      reason.description
  );

  // ============================================================
  // ICONS
  //
  // Icons remain frontend-controlled by position.
  // ============================================================

  const icons = [
    MapPinned,
    TrendingUp,
    Home,
    ShieldCheck,
    Sparkles,
    Clock3,
  ];

  // ============================================================
  // RENDER
  // ============================================================

  return (
    <section
      id="why-buy"
      aria-labelledby="why-buy-heading"
      className="
        relative
        overflow-hidden
        border-t
        border-[#e8e1d7]
        bg-white
        py-16
        sm:py-18
        md:py-20
        lg:py-24
      "
    >
      <div
        className="
          mx-auto
          max-w-[1380px]
          px-5
          sm:px-7
          lg:px-10
        "
      >
        {/* ======================================================
            HEADER
        ====================================================== */}

        <div className="max-w-[900px]">
          {/* EYEBROW */}

          <div
            className="
              flex
              items-center
              gap-3
              text-[10px]
              font-semibold
              uppercase
              tracking-[0.24em]
              text-[#8F7335]
              sm:text-[11px]
            "
          >
            <span className="h-px w-8 bg-[#C89D58]" />

            <span>{eyebrow}</span>
          </div>

          {/* TITLE */}

          <h2
            id="why-buy-heading"
            className="
              mt-4
              max-w-[850px]
              font-playfair
              text-[34px]
              font-medium
              leading-[1.08]
              tracking-[-0.025em]
              text-[#17342d]
              sm:text-[39px]
              md:text-[44px]
              lg:text-[48px]
            "
          >
            {title}
          </h2>

          {/* GOLD ACCENT */}

          <div className="mt-5 h-[2px] w-16 bg-[#C89D58]" />

          {/* ====================================================
              DESCRIPTION

              Supports BOTH:

              Plain text:
                "Choosing a property is about..."

              Rich HTML:
                "<p>Choosing a <strong>property</strong>...</p>"

              HTML is rendered safely through the existing
              trusted admin content using dangerouslySetInnerHTML.
          ==================================================== */}

          {hasRichText ? (
            <div
              className="
                mt-5
                max-w-[850px]
                break-words
                text-[13px]
                leading-[1.85]
                text-[#59635e]
                [overflow-wrap:anywhere]
                [word-break:break-word]

                [&_*]:max-w-full

                [&_p]:m-0
                [&_p]:mb-4
                [&_p:last-child]:mb-0
                [&_p]:break-words
                [&_p]:[overflow-wrap:anywhere]

                [&_strong]:font-semibold
                [&_strong]:text-[#263832]

                [&_b]:font-semibold
                [&_b]:text-[#263832]

                [&_em]:italic

                [&_u]:underline
                [&_u]:underline-offset-2

                [&_a]:font-medium
                [&_a]:text-[#A47A2B]
                [&_a]:underline
                [&_a]:underline-offset-2

                [&_ul]:mb-4
                [&_ul]:ml-5
                [&_ul]:max-w-full
                [&_ul]:list-disc

                [&_ol]:mb-4
                [&_ol]:ml-5
                [&_ol]:max-w-full
                [&_ol]:list-decimal

                [&_li]:mb-1
                [&_li]:break-words
                [&_li]:[overflow-wrap:anywhere]

                [&_h1]:max-w-full
                [&_h2]:max-w-full
                [&_h3]:max-w-full
                [&_h4]:max-w-full
                [&_h5]:max-w-full
                [&_h6]:max-w-full

                [&_h1]:font-playfair
                [&_h2]:font-playfair
                [&_h3]:font-playfair
                [&_h4]:font-playfair

                [&_h3]:mb-3
                [&_h3]:mt-5
                [&_h3]:text-xl
                [&_h3]:font-semibold
                [&_h3]:text-[#17342d]

                [&_h4]:mb-2
                [&_h4]:mt-4
                [&_h4]:font-semibold
                [&_h4]:text-[#17342d]

                [&_img]:h-auto
                [&_img]:max-w-full
                [&_img]:rounded-xl

                sm:text-[14px]
                md:text-[15px]
              "
              dangerouslySetInnerHTML={{
                __html:
                  normalizedDescription,
              }}
            />
          ) : (
            <div
              className="
                mt-5
                max-w-[850px]
                text-[13px]
                leading-[1.85]
                text-[#59635e]
                sm:text-[14px]
                md:text-[15px]
              "
            >
              {normalizedDescription
                .split(/\n\s*\n/)
                .map(
                  (
                    paragraph,
                    index
                  ) => (
                    <p
                      key={index}
                      className="
                        m-0
                        mb-4
                        last:mb-0
                        max-w-full
                        break-words
                        [overflow-wrap:anywhere]
                      "
                    >
                      {paragraph.trim()}
                    </p>
                  )
                )}
            </div>
          )}
        </div>

        {/* ======================================================
            REASONS
        ====================================================== */}

        <div
          className="
            mt-10
            grid
            grid-cols-1
            gap-4
            sm:grid-cols-2
            lg:grid-cols-3
            xl:grid-cols-6
          "
        >
          {reasons.map((reason, index) => {
            const Icon =
              icons[index % icons.length] ||
              Sparkles;

            return (
              <article
                key={`${reason.title || "reason"}-${index}`}
                className="
                  group
                  relative
                  flex
                  h-full
                  min-h-[235px]
                  flex-col
                  rounded-[20px]
                  border
                  border-[#e2dbd0]
                  bg-[#fbfaf7]
                  p-6
                  transition-all
                  duration-300
                  hover:-translate-y-1
                  hover:border-[#d2c4af]
                  hover:bg-white
                  hover:shadow-[0_18px_45px_rgba(23,52,45,0.08)]
                "
              >
                {/* TOP ACCENT */}

                <div
                  className="
                    absolute
                    left-6
                    top-0
                    h-[2px]
                    w-10
                    bg-[#C89D58]
                    opacity-70
                    transition-all
                    duration-300
                    group-hover:w-16
                  "
                />

                {/* ICON */}

                <div
                  className="
                    flex
                    h-11
                    w-11
                    shrink-0
                    items-center
                    justify-center
                    rounded-[13px]
                    border
                    border-[#D4AF37]/35
                    bg-[#f5f0e7]
                    text-[#A9822E]
                    transition-all
                    duration-300
                    group-hover:border-[#C89D58]/50
                    group-hover:bg-[#17342d]
                    group-hover:text-[#D4AF37]
                  "
                >
                  <Icon
                    size={20}
                    strokeWidth={1.6}
                  />
                </div>

                {/* NUMBER */}

                <span
                  className="
                    absolute
                    right-5
                    top-5
                    text-[10px]
                    font-semibold
                    tracking-[0.12em]
                    text-[#b7afa3]
                  "
                >
                  {String(index + 1).padStart(
                    2,
                    "0"
                  )}
                </span>

                {/* TITLE */}

                <h3
                  className="
                    mt-6
                    text-[15px]
                    font-semibold
                    leading-[1.35]
                    text-[#17342d]
                    sm:text-[16px]
                  "
                >
                  {reason.title}
                </h3>

                {/* DESCRIPTION */}

                <p
                  className="
                    mt-3
                    text-[12px]
                    leading-[1.75]
                    text-[#6d746f]
                    sm:text-[13px]
                  "
                >
                  {reason.description}
                </p>

                {/* BOTTOM DETAIL */}

                <div
                  className="
                    mt-auto
                    pt-6
                  "
                >
                  <div
                    className="
                      h-px
                      w-full
                      bg-[#e9e3da]
                    "
                  />

                  <div
                    className="
                      mt-4
                      flex
                      items-center
                      gap-2
                      text-[10px]
                      font-semibold
                      uppercase
                      tracking-[0.12em]
                      text-[#8F7335]
                    "
                  >
                    <span
                      className="
                        h-1.5
                        w-1.5
                        rounded-full
                        bg-[#C89D58]
                      "
                    />

                    Location Factor
                  </div>
                </div>
              </article>
            );
          })}
        </div>
      </div>
    </section>
  );
}