import {
  TrendingUp,
  BarChart3,
  WalletCards,
  Sparkles,
  Calculator,
  ShieldCheck,
  Leaf,
} from "lucide-react";

/* =========================================================
   ROI EXPLAINER / EDUCATIONAL SECTION
========================================================= */

export default function ROIExplainerSection() {
  const metrics = [
    {
      icon: TrendingUp,
      title: "Equity ROI",
      short: "Total return on your invested equity",
      description:
        "Equity ROI measures how much profit your investment generates compared with the initial equity you put into the property.",
      formula:
        "Equity ROI = Total Profit ÷ Initial Equity × 100",
    },
    {
      icon: BarChart3,
      title: "Annualized ROI (IRR)",
      short: "Your estimated yearly investment return",
      description:
        "IRR considers the timing of your cash flows, including your initial investment, rental cash flow and the value received when the property is sold.",
      formula:
        "IRR = Annualized return that makes all investment cash flows equal to zero",
    },
    {
      icon: WalletCards,
      title: "Rental Income",
      short: "Recurring income generated by the property",
      description:
        "Rental income represents the cash generated by leasing the property. Your calculator deducts the operating expenses you enter to arrive at net rental income.",
      formula:
        "Net Rental Income = Rental Income − Operating Expenses",
    },
    {
      icon: Sparkles,
      title: "Property Appreciation",
      short: "Increase in the property's estimated value",
      description:
        "Property appreciation represents the projected increase in the property's value over your selected holding period based on the appreciation assumption used by the calculator.",
      formula:
        "Appreciation = Future Property Value − Initial Property Value",
    },
    {
      icon: Calculator,
      title: "Cash-on-Cash Return",
      short: "Annual cash return on your equity",
      description:
        "Cash-on-cash return focuses on the property's annual rental cash flow relative to the initial equity invested. It is useful for evaluating ongoing income performance.",
      formula:
        "Cash-on-Cash = Annual Rental Cash Flow ÷ Initial Equity × 100",
    },
    {
      icon: ShieldCheck,
      title: "Equity Break-Even",
      short: "When your initial equity is projected to be recovered",
      description:
        "Equity break-even occurs when the projected property equity plus cumulative rental cash flow recovers your original equity contribution.",
      formula:
        "Break-Even = Property Equity + Cumulative Cash Flow − Initial Equity",
    },
  ];

  return (
    <section className="relative overflow-hidden bg-[#faf9f6] py-10 md:py-14">
      {/* =====================================================
          BACKGROUND DETAILS
      ===================================================== */}

      <div
        className="
          pointer-events-none
          absolute
          -left-32
          top-20
          h-[300px]
          w-[300px]
          rounded-full
          bg-[#d5a449]/[0.07]
          blur-[90px]
        "
      />

      <div
        className="
          pointer-events-none
          absolute
          -right-32
          bottom-10
          h-[320px]
          w-[320px]
          rounded-full
          bg-[#176b51]/[0.06]
          blur-[100px]
        "
      />

      <div className="relative z-10 mx-auto max-w-[1450px] px-5 xl:px-8">
        {/* ===================================================
            INTRO HEADER
        =================================================== */}

        <div className="mx-auto max-w-[850px] text-center">
          {/* EYEBROW */}

          <div className="flex items-center justify-center gap-2">
            <span
              className="
                h-[5px]
                w-[5px]
                rounded-full
                bg-[#c9a64b]
                shadow-[0_0_10px_rgba(201,166,75,0.55)]
              "
            />

            <p
              className="
                text-[8px]
                font-semibold
                uppercase
                tracking-[0.24em]
                text-[#b88b36]
              "
            >
              Real Estate Investment Guide
            </p>

            <span
              className="
                h-[5px]
                w-[5px]
                rounded-full
                bg-[#c9a64b]
                shadow-[0_0_10px_rgba(201,166,75,0.55)]
              "
            />
          </div>

          {/* TITLE */}

          <h2
            className="
              mt-3
              font-serif
              text-[27px]
              leading-tight
              text-[#10251f]
              sm:text-[31px]
              md:text-[35px]
            "
          >
            Understanding ROI in Real Estate
          </h2>

          {/* DESCRIPTION */}

          <p
            className="
              mx-auto
              mt-3
              max-w-[720px]
              text-[10px]
              leading-[1.9]
              text-[#777]
              sm:text-[11px]
            "
          >
            Real estate returns are influenced by more than just property
            appreciation. Rental income, financing costs, equity growth and
            the time you hold the property all contribute to your overall
            investment performance.
          </p>
        </div>

        {/* ===================================================
            MAIN EXPLANATION CARD
        =================================================== */}

        <div
          className="
            mt-7
            overflow-hidden
            rounded-[14px]
            border
            border-[#e5ded2]
            bg-white
            shadow-[0_12px_45px_rgba(16,37,31,0.045)]
          "
        >
          {/* TOP DARK INTRO */}

          <div
            className="
              relative
              overflow-hidden
              bg-[#002b20]
              px-5
              py-6
              md:px-7
              md:py-7
            "
          >
            {/* GLOW */}

            <div
              className="
                pointer-events-none
                absolute
                -right-20
                -top-24
                h-[230px]
                w-[230px]
                rounded-full
                bg-[#d5a449]/[0.08]
                blur-[70px]
              "
            />

            <div
              className="
                pointer-events-none
                absolute
                -left-20
                -bottom-28
                h-[230px]
                w-[230px]
                rounded-full
                bg-[#176b51]/30
                blur-[75px]
              "
            />

            <div className="relative z-10 grid grid-cols-1 gap-6 md:grid-cols-[1fr_auto] md:items-center">
              {/* COPY */}

              <div>
                <div className="flex items-center gap-2">
                  <div
                    className="
                      flex
                      h-[30px]
                      w-[30px]
                      items-center
                      justify-center
                      rounded-full
                      border
                      border-[#d5a449]/25
                      bg-[#d5a449]/[0.08]
                    "
                  >
                    <Calculator
                      size={15}
                      strokeWidth={1.5}
                      className="text-[#d8b15e]"
                    />
                  </div>

                  <p
                    className="
                      text-[8px]
                      font-semibold
                      uppercase
                      tracking-[0.18em]
                      text-[#d5a449]
                    "
                  >
                    The Basics
                  </p>
                </div>

                <h3
                  className="
                    mt-3
                    font-serif
                    text-[21px]
                    leading-tight
                    text-white
                    md:text-[24px]
                  "
                >
                  What does ROI actually mean?
                </h3>

                <p
                  className="
                    mt-2
                    max-w-[720px]
                    text-[9px]
                    leading-[1.9]
                    text-white/60
                    md:text-[10px]
                  "
                >
                  ROI, or Return on Investment, tells you how much your
                  investment has earned relative to the money you initially
                  invested. In real estate, this return can come from
                  multiple sources — property appreciation, rental income
                  and the growth of your ownership equity.
                </p>
              </div>

              {/* FORMULA */}

              <div
                className="
                  min-w-0
                  rounded-[10px]
                  border
                  border-white/10
                  bg-white/[0.045]
                  px-5
                  py-4
                  md:min-w-[260px]
                "
              >
                <p
                  className="
                    text-[7px]
                    font-semibold
                    uppercase
                    tracking-[0.18em]
                    text-white/40
                  "
                >
                  Simple ROI Formula
                </p>

                <p
                  className="
                    mt-2
                    font-serif
                    text-[15px]
                    leading-tight
                    text-[#d8b15e]
                  "
                >
                  ROI = Profit ÷ Investment × 100
                </p>

                <p
                  className="
                    mt-2
                    text-[8px]
                    leading-4
                    text-white/45
                  "
                >
                  A higher ROI generally indicates a stronger return relative
                  to the capital invested.
                </p>
              </div>
            </div>

            {/* GOLD LINE */}

            <div
              className="
                absolute
                inset-x-0
                bottom-0
                h-px
                bg-gradient-to-r
                from-transparent
                via-[#d5a449]/60
                to-transparent
              "
            />
          </div>

          {/* =================================================
              METRIC GRID
          ================================================= */}

          <div
            className="
              grid
              grid-cols-1
              sm:grid-cols-2
              lg:grid-cols-3
            "
          >
            {metrics.map((metric, index) => {
              const Icon = metric.icon;

              const isLastInRow =
                index === metrics.length - 1;

              return (
                <div
                  key={metric.title}
                  className={`
                    group
                    relative
                    p-5
                    transition-all
                    duration-300
                    hover:bg-[#fbfaf7]
                    md:p-6
                    ${
                      !isLastInRow
                        ? "border-b border-[#eee8de]"
                        : ""
                    }
                    sm:border-r
                    sm:border-[#eee8de]
                    ${
                      index >= 4
                        ? "lg:border-b-0"
                        : ""
                    }
                    ${
                      index === 2 || index === 5
                        ? "lg:border-r-0"
                        : ""
                    }
                  `}
                >
                  {/* ICON */}

                  <div
                    className="
                      flex
                      h-[38px]
                      w-[38px]
                      items-center
                      justify-center
                      rounded-[10px]
                      bg-[#f3eee4]
                      transition-all
                      duration-300
                      group-hover:bg-[#e9f1ec]
                    "
                  >
                    <Icon
                      size={17}
                      strokeWidth={1.5}
                      className="
                        text-[#b88b36]
                        transition-colors
                        duration-300
                        group-hover:text-[#176b51]
                      "
                    />
                  </div>

                  {/* TITLE */}

                  <h4
                    className="
                      mt-4
                      font-serif
                      text-[17px]
                      leading-tight
                      text-[#10251f]
                    "
                  >
                    {metric.title}
                  </h4>

                  {/* SHORT DESCRIPTION */}

                  <p
                    className="
                      mt-1
                      text-[9px]
                      font-medium
                      text-[#176b51]
                    "
                  >
                    {metric.short}
                  </p>

                  {/* EXPLANATION */}

                  <p
                    className="
                      mt-3
                      text-[9px]
                      leading-[1.8]
                      text-[#777]
                    "
                  >
                    {metric.description}
                  </p>

                  {/* FORMULA */}

                  <div
                    className="
                      mt-4
                      rounded-[7px]
                      border
                      border-[#e8e1d7]
                      bg-[#fbfaf7]
                      px-3
                      py-2.5
                    "
                  >
                    <p
                      className="
                        text-[7px]
                        font-semibold
                        uppercase
                        tracking-[0.12em]
                        text-[#9a927f]
                      "
                    >
                      Key Formula
                    </p>

                    <p
                      className="
                        mt-1
                        text-[8px]
                        leading-4
                        text-[#4f554f]
                      "
                    >
                      {metric.formula}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* ===================================================
            HOW RETURNS ARE CREATED
        =================================================== */}

        <div
          className="
            mt-5
            grid
            grid-cols-1
            gap-4
            lg:grid-cols-[1.1fr_0.9fr]
          "
        >
          {/* LEFT — RETURN SOURCES */}

          <div
            className="
              rounded-[12px]
              border
              border-[#e5ded2]
              bg-white
              p-5
              md:p-6
            "
          >
            <div className="flex items-center gap-3">
              <div
                className="
                  flex
                  h-[36px]
                  w-[36px]
                  items-center
                  justify-center
                  rounded-full
                  bg-[#f4ecd9]
                "
              >
                <BarChart3
                  size={17}
                  strokeWidth={1.5}
                  className="text-[#b88b36]"
                />
              </div>

              <div>
                <p
                  className="
                    text-[7px]
                    font-semibold
                    uppercase
                    tracking-[0.16em]
                    text-[#9a927f]
                  "
                >
                  Return Structure
                </p>

                <h3
                  className="
                    mt-1
                    font-serif
                    text-[19px]
                    leading-tight
                    text-[#10251f]
                  "
                >
                  Where do real estate returns come from?
                </h3>
              </div>
            </div>

            <p
              className="
                mt-4
                text-[9px]
                leading-[1.9]
                text-[#777]
              "
            >
              A real estate investment can generate returns through several
              different channels. Understanding each one helps you evaluate
              whether an investment is primarily an income opportunity,
              an appreciation opportunity, or a combination of both.
            </p>

            {/* RETURN FLOW */}

            <div className="mt-5 space-y-3">
              <ReturnSource
                number="01"
                title="Rental Income"
                description="Recurring income generated by leasing the property."
                icon={WalletCards}
              />

              <ReturnSource
                number="02"
                title="Property Appreciation"
                description="Growth in the market value of the property over time."
                icon={TrendingUp}
              />

              <ReturnSource
                number="03"
                title="Equity Growth"
                description="As loan principal is repaid, your ownership stake in the property increases."
                icon={ShieldCheck}
              />

              <ReturnSource
                number="04"
                title="Leverage"
                description="Financing can allow you to control a larger property with less initial equity, increasing both potential returns and risk."
                icon={BarChart3}
              />
            </div>
          </div>

          {/* RIGHT — EXAMPLE */}

          <div
            className="
              relative
              overflow-hidden
              rounded-[12px]
              border
              border-[#24493d]
              bg-[#002b20]
              p-5
              md:p-6
            "
          >
            {/* BACKGROUND GLOW */}

            <div
              className="
                pointer-events-none
                absolute
                -right-20
                -top-20
                h-[200px]
                w-[200px]
                rounded-full
                bg-[#d5a449]/[0.08]
                blur-[70px]
              "
            />

            <div className="relative z-10">
              <div className="flex items-center gap-2">
                <Leaf
                  size={15}
                  strokeWidth={1.5}
                  className="text-[#d5a449]"
                />

                <p
                  className="
                    text-[7px]
                    font-semibold
                    uppercase
                    tracking-[0.18em]
                    text-[#d5a449]
                  "
                >
                  Simple Example
                </p>
              </div>

              <h3
                className="
                  mt-3
                  font-serif
                  text-[20px]
                  leading-tight
                  text-white
                "
              >
                How an investment can build wealth
              </h3>

              <p
                className="
                  mt-2
                  text-[9px]
                  leading-[1.9]
                  text-white/55
                "
              >
                Imagine you purchase a property for ₹2.5 Cr and invest
                ₹75 L as your initial equity. Over the holding period,
                your returns may come from both rental income and an
                increase in property value.
              </p>

              {/* EXAMPLE METRICS */}

              <div className="mt-5 space-y-2">
                <ExampleRow
                  label="Initial Property Value"
                  value="₹ 2.50 Cr"
                />

                <ExampleRow
                  label="Initial Equity"
                  value="₹ 75 L"
                />

                <ExampleRow
                  label="Monthly Rental Income"
                  value="₹ 50,000"
                />

                <ExampleRow
                  label="Potential Appreciation"
                  value="Depends on market"
                />
              </div>

              {/* NOTE */}

              <div
                className="
                  mt-5
                  rounded-[8px]
                  border
                  border-white/10
                  bg-white/[0.04]
                  px-3
                  py-3
                "
              >
                <p
                  className="
                    text-[8px]
                    leading-[1.8]
                    text-white/45
                  "
                >
                  The example above is illustrative only. Actual returns
                  depend on purchase price, financing, rent, vacancy,
                  expenses, market conditions, taxes and selling costs.
                </p>
              </div>
            </div>

            {/* GOLD LINE */}

            <div
              className="
                absolute
                inset-x-0
                bottom-0
                h-px
                bg-gradient-to-r
                from-transparent
                via-[#d5a449]/60
                to-transparent
              "
            />
          </div>
        </div>

        {/* ===================================================
            IMPORTANT CONSIDERATIONS
        =================================================== */}

        <div
          className="
            mt-5
            rounded-[12px]
            border
            border-[#e5ded2]
            bg-white
            px-5
            py-5
            md:px-6
          "
        >
          <div
            className="
              flex
              flex-col
              gap-4
              md:flex-row
              md:items-start
              md:justify-between
            "
          >
            <div className="flex items-start gap-3">
              <div
                className="
                  flex
                  h-[34px]
                  w-[34px]
                  shrink-0
                  items-center
                  justify-center
                  rounded-full
                  bg-[#f8eee9]
                "
              >
                <ShieldCheck
                  size={16}
                  strokeWidth={1.5}
                  className="text-[#a56d45]"
                />
              </div>

              <div>
                <h3
                  className="
                    font-serif
                    text-[18px]
                    text-[#10251f]
                  "
                >
                  ROI is a projection, not a guarantee
                </h3>

                <p
                  className="
                    mt-2
                    max-w-[900px]
                    text-[9px]
                    leading-[1.8]
                    text-[#777]
                  "
                >
                  Real estate returns can vary significantly based on
                  market conditions, property location, rental demand,
                  financing terms, vacancy, maintenance costs, taxation
                  and the eventual selling price. Use the calculator to
                  compare scenarios rather than treating the output as
                  a guaranteed future return.
                </p>
              </div>
            </div>

            <div
              className="
                shrink-0
                rounded-[8px]
                border
                border-[#e6dfd4]
                bg-[#fbfaf7]
                px-4
                py-3
                md:max-w-[300px]
              "
            >
              <p
                className="
                  text-[8px]
                  font-semibold
                  text-[#17382e]
                "
              >
                Best practice
              </p>

              <p
                className="
                  mt-1
                  text-[8px]
                  leading-4
                  text-[#888]
                "
              >
                Test conservative, base-case and optimistic scenarios
                before making an investment decision.
              </p>
            </div>
          </div>
        </div>

        {/* ===================================================
            BOTTOM CTA
        =================================================== */}

        <div className="mt-5 text-center">
          <p
            className="
              text-[8px]
              font-semibold
              uppercase
              tracking-[0.2em]
              text-[#9a927f]
            "
          >
            Ready to evaluate an opportunity?
          </p>

          <h3
            className="
              mt-2
              font-serif
              text-[21px]
              text-[#10251f]
              md:text-[23px]
            "
          >
            Use the calculator above to model your investment
          </h3>

          <p
            className="
              mx-auto
              mt-2
              max-w-[620px]
              text-[9px]
              leading-[1.8]
              text-[#888]
            "
          >
            Adjust your property value, financing, rental income,
            expenses and holding period to understand how different
            assumptions can change your projected returns.
          </p>
        </div>

        {/* ===================================================
            DISCLAIMER
        =================================================== */}

        <p
          className="
            mx-auto
            mt-6
            max-w-[1000px]
            text-center
            text-[8px]
            leading-4
            text-[#aaa]
          "
        >
          This educational content is for informational purposes only and
          does not constitute financial, investment, tax or legal advice.
          Calculated returns are estimates based on the assumptions entered
          into the calculator and may differ materially from actual results.
        </p>
      </div>
    </section>
  );
}

/* =========================================================
   RETURN SOURCE
========================================================= */

function ReturnSource({
  number,
  title,
  description,
  icon: Icon,
}) {
  return (
    <div
      className="
        group
        flex
        items-start
        gap-3
        rounded-[9px]
        border
        border-[#eee8de]
        bg-[#fbfaf7]
        p-3
        transition-all
        duration-300
        hover:border-[#d9d0c0]
        hover:bg-white
      "
    >
      {/* NUMBER */}

      <div
        className="
          flex
          h-[28px]
          w-[28px]
          shrink-0
          items-center
          justify-center
          rounded-full
          bg-[#f0eadf]
          text-[7px]
          font-semibold
          text-[#a07a32]
        "
      >
        {number}
      </div>

      {/* ICON */}

      <div
        className="
          flex
          h-[28px]
          w-[28px]
          shrink-0
          items-center
          justify-center
          rounded-full
          bg-[#e9f1ec]
        "
      >
        <Icon
          size={13}
          strokeWidth={1.5}
          className="text-[#176b51]"
        />
      </div>

      {/* CONTENT */}

      <div className="min-w-0">
        <p
          className="
            text-[9px]
            font-semibold
            text-[#333]
          "
        >
          {title}
        </p>

        <p
          className="
            mt-1
            text-[8px]
            leading-4
            text-[#888]
          "
        >
          {description}
        </p>
      </div>
    </div>
  );
}

/* =========================================================
   EXAMPLE ROW
========================================================= */

function ExampleRow({
  label,
  value,
}) {
  return (
    <div
      className="
        flex
        items-center
        justify-between
        gap-4
        border-b
        border-white/10
        py-2.5
        last:border-0
      "
    >
      <span
        className="
          text-[8px]
          text-white/50
        "
      >
        {label}
      </span>

      <span
        className="
          text-right
          text-[9px]
          font-medium
          text-white
        "
      >
        {value}
      </span>
    </div>
  );
}